var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/safety/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1lzrhcv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c5pvlo._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1a72a79._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/_1t4fbke._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_safety_page_actions_1mh60cv.js")
R.m(41962)
module.exports=R.m(41962).exports
