var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1w6ncqe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/_1hdlb6h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1tjawz5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09pqrv0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xpcv9w._.js")
R.c("server/chunks/ssr/_1t4fbke._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_[slug]_page_actions_0plgz8u.js")
R.m(66387)
module.exports=R.m(66387).exports
