var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/[slug]/on-board/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ly5sed._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c5pvlo._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1a72a79._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/_1t4fbke._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_[slug]_on-board_page_actions_1vo9a_2.js")
R.m(51940)
module.exports=R.m(51940).exports
